---
###############################################
# F5 BIG-IP APM SAML Solution Cleanup (Automated)
# Solution 3: SAML Service Provider with Okta IDP
###############################################
#
# Purpose: Automated cleanup without confirmation prompts
# Use this for CI/CD pipelines or automated teardown
#
# IMPORTANT: This playbook deletes all configured objects
# WITHOUT confirmation prompts
#
# Usage:
#   ansible-playbook cleanup_apm_saml.yml
#
###############################################

- name: Cleanup F5 BIG-IP APM SAML Solution (Automated)
  hosts: bigip
  gather_facts: no
  connection: local
  vars_files:
    - vars/solution3.yml

  tasks:
    - name: Display cleanup banner
      debug:
        msg: |
          ============================================
          APM SAML Solution Automated Cleanup
          ============================================
          Removing all components for: {{ vs1_name }}
          Target: {{ bigip_mgmt }}
          ============================================

    - name: Verify BIG-IP connectivity
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/info"
        method: GET
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200]
        timeout: 30
      delegate_to: localhost
      register: bigip_check

    ###############################################
    # GSLB Cleanup
    ###############################################

    - name: Delete GSLB Wide-IP
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/declare/{{ partition_name }}-gslb"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: gslb_delete
      ignore_errors: yes
      when: create_gslb | default(false)

    ###############################################
    # AS3 Application Cleanup
    ###############################################

    - name: Delete AS3 application
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/declare/{{ partition_name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: as3_delete
      ignore_errors: yes
      when: create_as3_application | default(false)

    ###############################################
    # APM Objects Cleanup
    ###############################################

    - name: Delete access profile
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/profile/access/~Common~{{ access_profile.name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: profile_delete
      ignore_errors: yes

    - name: Delete policy items
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/policy/policy-item/~Common~{{ item }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      loop:
        - "{{ policy_items.start.name }}"
        - "{{ policy_items.saml_auth.name }}"
        - "{{ policy_items.allow_ending.name }}"
        - "{{ policy_items.deny_ending.name }}"
      ignore_errors: yes

    - name: Delete policy agents
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/policy/agent/{{ item.type }}/~Common~{{ item.name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      loop:
        - { type: "aaa-saml", name: "{{ policy_agents.saml_auth.name }}" }
        - { type: "ending-allow", name: "{{ policy_agents.allow_ending.name }}" }
        - { type: "ending-deny", name: "{{ policy_agents.deny_ending.name }}" }
      ignore_errors: yes

    - name: Delete access policy
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/policy/access-policy/~Common~{{ access_policy.name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: policy_delete
      ignore_errors: yes

    - name: Delete customization groups
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/policy/customization-group/~Common~{{ vs1_name }}-psp_{{ item }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      loop:
        - "logout"
        - "eps"
        - "errormap"
        - "framework_installation"
        - "general_ui"
        - "end_deny_ag"
      ignore_errors: yes

    - name: Delete SAML Service Provider
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/aaa/saml/~Common~{{ saml_sp.name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: saml_sp_delete
      ignore_errors: yes

    - name: Delete SAML IDP Connector
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/aaa/saml-idp-connector/~Common~{{ saml_idp.name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: idp_connector_delete
      ignore_errors: yes

    - name: Delete IDP certificate
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/sys/crypto/cert/~Common~{{ saml_idp.certificate_name }}.crt"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: cert_delete
      ignore_errors: yes

    ###############################################
    # Cleanup Summary
    ###############################################

    - name: Display cleanup summary
      debug:
        msg: |
          ============================================
          Cleanup Complete!
          ============================================

          Solution {{ vs1_name }} cleanup results:

          {% if create_gslb | default(false) %}
          GSLB: {{ 'Deleted' if gslb_delete.status == 200 else 'Not found' }}
          {% endif %}
          {% if create_as3_application | default(false) %}
          AS3 Application: {{ 'Deleted' if as3_delete.status == 200 else 'Not found' }}
          {% endif %}
          Access Profile: {{ 'Deleted' if profile_delete.status == 200 else 'Not found' }}
          Access Policy: {{ 'Deleted' if policy_delete.status == 200 else 'Not found' }}
          SAML SP: {{ 'Deleted' if saml_sp_delete.status == 200 else 'Not found' }}
          SAML IDP Connector: {{ 'Deleted' if idp_connector_delete.status == 200 else 'Not found' }}
          IDP Certificate: {{ 'Deleted' if cert_delete.status == 200 else 'Not found' }}

          ============================================
