---
###############################################
# F5 BIG-IP APM SAML Solution Delete
# Solution 3: SAML Service Provider with Okta IDP
###############################################
#
# Purpose: Remove all SAML solution components
# Based on: solution3-delete Postman collection
#
# IMPORTANT: This playbook deletes all configured objects
# Use with caution - this action cannot be undone
#
# Usage:
#   ansible-playbook delete_apm_saml.yml
#   ansible-playbook delete_apm_saml.yml -e "confirm_delete=true"  # Skip confirmation
#
###############################################

- name: Delete F5 BIG-IP APM SAML Solution
  hosts: bigip
  gather_facts: no
  connection: local
  vars_files:
    - vars/solution3.yml

  vars:
    # Prompt for confirmation by default
    confirm_delete: false

  tasks:
    - name: Display deletion warning
      debug:
        msg: |
          ============================================
          WARNING: APM SAML Solution Deletion
          ============================================
          This will DELETE all components for: {{ vs1_name }}

          Components to be removed:
          {% if create_gslb | default(false) %}
          - GSLB Wide-IP: {{ dns1_name }}
          {% endif %}
          {% if create_as3_application | default(false) %}
          - AS3 Application Tenant: {{ partition_name }}
          {% endif %}
          - Access Profile: /Common/{{ access_profile.name }}
          - Access Policy: /Common/{{ access_policy.name }}
          - SAML Service Provider: /Common/{{ saml_sp.name }}
          - SAML IDP Connector: /Common/{{ saml_idp.name }}
          - IDP Certificate: /Common/{{ saml_idp.certificate_name }}
          - All policy items and agents
          - All customization groups

          Target: {{ bigip_mgmt }}

          This action CANNOT be undone!
          ============================================

    - name: Confirm deletion
      pause:
        prompt: "Type 'DELETE' to confirm deletion (Ctrl+C to cancel)"
      register: confirmation
      when: not confirm_delete | bool

    - name: Validate confirmation
      assert:
        that:
          - confirmation.user_input == "DELETE"
        fail_msg: "Deletion cancelled - confirmation text did not match"
      when: not confirm_delete | bool

    - name: Verify BIG-IP connectivity
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/info"
        method: GET
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200]
        timeout: 30
      delegate_to: localhost
      register: bigip_check

    - name: Display connection status
      debug:
        msg: "Connected to BIG-IP - Starting deletion process..."

    ###############################################
    # GSLB Cleanup (Optional)
    ###############################################

    - name: Delete GSLB Wide-IP (AS3)
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/declare/{{ partition_name }}-gslb"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: gslb_delete
      ignore_errors: yes
      when: create_gslb | default(false)

    - name: Display GSLB deletion result
      debug:
        msg: "GSLB Wide-IP {{ dns1_name }} - {{ 'deleted' if gslb_delete.status == 200 else 'not found' }}"
      when: create_gslb | default(false)

    ###############################################
    # AS3 Application Deletion
    ###############################################

    - name: Delete AS3 application
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/declare/{{ partition_name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: as3_delete
      ignore_errors: yes
      when: create_as3_application | default(false)

    - name: Display AS3 deletion result
      debug:
        msg: "AS3 Application {{ partition_name }} - {{ 'deleted' if as3_delete.status == 200 else 'not found' }}"
      when: create_as3_application | default(false)

    ###############################################
    # Access Profile and Policy Deletion
    ###############################################

    - name: Delete access profile
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/profile/access/~Common~{{ access_profile.name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: profile_delete
      ignore_errors: yes

    - name: Display access profile deletion result
      debug:
        msg: "Access Profile {{ access_profile.name }} - {{ 'deleted' if profile_delete.status == 200 else 'not found' }}"

    - name: Delete access policy
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/policy/access-policy/~Common~{{ access_policy.name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: policy_delete
      ignore_errors: yes

    - name: Display access policy deletion result
      debug:
        msg: "Access Policy {{ access_policy.name }} - {{ 'deleted' if policy_delete.status == 200 else 'not found' }}"

    ###############################################
    # SAML Objects Deletion
    ###############################################

    - name: Delete SAML Service Provider
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/aaa/saml/~Common~{{ saml_sp.name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: saml_sp_delete
      ignore_errors: yes

    - name: Display SAML SP deletion result
      debug:
        msg: "SAML SP {{ saml_sp.name }} - {{ 'deleted' if saml_sp_delete.status == 200 else 'not found' }}"

    - name: Delete SAML IDP Connector
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/aaa/saml-idp-connector/~Common~{{ saml_idp.name }}"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: idp_connector_delete
      ignore_errors: yes

    - name: Display SAML IDP Connector deletion result
      debug:
        msg: "SAML IDP Connector {{ saml_idp.name }} - {{ 'deleted' if idp_connector_delete.status == 200 else 'not found' }}"

    ###############################################
    # Certificate Cleanup
    ###############################################

    - name: Delete IDP certificate
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/sys/crypto/cert/~Common~{{ saml_idp.certificate_name }}.crt"
        method: DELETE
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: cert_delete
      ignore_errors: yes

    - name: Display certificate deletion result
      debug:
        msg: "IDP Certificate {{ saml_idp.certificate_name }} - {{ 'deleted' if cert_delete.status == 200 else 'not found' }}"

    ###############################################
    # Deletion Summary
    ###############################################

    - name: Display deletion summary
      debug:
        msg: |
          ============================================
          Deletion Complete!
          ============================================

          Solution {{ vs1_name }} has been removed.

          Deleted Components:
          {% if create_gslb | default(false) %}
          - GSLB Wide-IP: {{ 'Yes' if gslb_delete.status == 200 else 'Not found' }}
          {% endif %}
          {% if create_as3_application | default(false) %}
          - AS3 Application: {{ 'Yes' if as3_delete.status == 200 else 'Not found' }}
          {% endif %}
          - Access Profile: {{ 'Yes' if profile_delete.status == 200 else 'Not found' }}
          - Access Policy: {{ 'Yes' if policy_delete.status == 200 else 'Not found' }}
          - SAML SP Service: {{ 'Yes' if saml_sp_delete.status == 200 else 'Not found' }}
          - SAML IDP Connector: {{ 'Yes' if idp_connector_delete.status == 200 else 'Not found' }}
          - IDP Certificate: {{ 'Yes' if cert_delete.status == 200 else 'Not found' }}

          Note: Policy items, agents, and customization groups
          are automatically removed when the access policy is deleted.

          To redeploy, run:
            ansible-playbook deploy_apm_saml.yml

          ============================================
