---
###############################################
# F5 BIG-IP APM SAML Identity Provider Deployment
# Solution 4: SAML IDP with AD Authentication
###############################################
#
# This playbook deploys a complete APM SAML IDP solution with:
# - SAML Service Provider connector
# - SAML Identity Provider service
# - Active Directory authentication
# - Access policy with logon page
# - APM access profile with SSO
# - Optional AS3 application deployment
# - Optional GSLB/DNS configuration
#
# Source: Converted from solution4-create Postman collection
# https://github.com/f5devcentral/access-solutions/blob/master/solution4/postman/solution4-create.postman_collection.json
#
# Usage:
#   ansible-playbook deploy_apm_saml_idp.yml
#   ansible-playbook deploy_apm_saml_idp.yml --limit bigip-01
#   ansible-playbook deploy_apm_saml_idp.yml -e "@vars/solution4.yml"
#
###############################################

- name: Deploy F5 BIG-IP APM SAML IDP Solution
  hosts: bigip
  gather_facts: no
  connection: local
  vars_files:
    - vars/solution4.yml

  tasks:
    - name: Display deployment information
      debug:
        msg: |
          ============================================
          APM SAML Identity Provider Solution Deployment
          ============================================

          Solution Name: {{ vs1_name }}
          IDP DNS Name: {{ dns1_name }}
          SP DNS Name: {{ dns2_name }}
          Customization Type: {{ custom_type }}

          SAML Configuration:
          - Identity Provider Entity ID: {{ saml_idp_service.entity_id }}
          - Service Provider Entity ID: {{ saml_sp_connector.entity_id }}
          - ACS URL: {{ saml_sp_connector.acs_url }}
          - Assertion Validity: {{ saml_idp_service.assertion_validity }}s

          Active Directory:
          - Domain: {{ ad_aaa_server.domain }}
          - Domain Controllers: {{ ad_aaa_server.domain_controllers | map(attribute='name') | join(', ') }}

          Components to Deploy:
          - AD Server Pool and AAA Configuration
          - SAML SP Connector ({{ saml_sp_connector.name }})
          - SAML IDP Service ({{ saml_idp_service.name }})
          - Access Policy with Logon Page → AD Auth flow
          - APM Access Profile with SSO
          {% if create_as3_application | default(false) %}
          - AS3 Virtual Server Application
          {% endif %}
          {% if create_gslb | default(false) %}
          - GSLB/DNS Configuration
          {% endif %}

          ============================================

    - name: Verify BIG-IP connectivity
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/info"
        method: GET
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        status_code: [200]
        timeout: 30
      delegate_to: localhost
      register: bigip_check
      failed_when: bigip_check.status != 200

    - name: Display BIG-IP AS3 version
      debug:
        msg: "BIG-IP connectivity verified - AS3 version: {{ bigip_check.json.version | default('N/A') }}"

    ###############################################
    # AD Pool and AAA Server Configuration (BEFORE Transaction)
    ###############################################

    - name: Create AD server pool
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/ltm/pool"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        body_format: json
        body:
          name: "{{ ad_pool.name }}"
          partition: "Common"
          members:
            - name: "{{ ad_pool.members[0].address }}:{{ ad_pool.members[0].port }}"
              address: "{{ ad_pool.members[0].address }}"
          monitor: "{{ ad_pool.monitor }}"
        status_code: [200, 201, 409]
        timeout: 30
      delegate_to: localhost
      register: ad_pool_result

    - name: Create AAA Active Directory server
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/aaa/active-directory"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        body_format: json
        body:
          name: "{{ ad_aaa_server.name }}"
          partition: "Common"
          adminEncryptedPassword: "{{ ad_aaa_server.admin_password }}"
          adminName: "{{ ad_aaa_server.admin_name }}"
          domain: "{{ ad_aaa_server.domain }}"
          pool: "{{ ad_aaa_server.pool }}"
          timeout: "{{ ad_aaa_server.timeout }}"
          groupCacheTtl: "{{ ad_aaa_server.group_cache_ttl }}"
          psoCacheTtl: "{{ ad_aaa_server.pso_cache_ttl }}"
          usePool: "{{ ad_aaa_server.use_pool }}"
          locationSpecific: "{{ ad_aaa_server.location_specific }}"
          cleanupCache: "none"
          kdcLockoutDuration: 0
          padata: "none"
          domainControllers:
            - name: "{{ ad_aaa_server.domain_controllers[0].name }}"
              ip: "{{ ad_aaa_server.domain_controllers[0].ip }}"
        status_code: [200, 201, 409]
        timeout: 30
      delegate_to: localhost
      register: ad_aaa_result

    - name: Display AD configuration status
      debug:
        msg:
          - "AD Pool Status: {{ ad_pool_result.status }}"
          - "AD AAA Server Status: {{ ad_aaa_result.status }}"
          - "AD Domain: {{ ad_aaa_server.domain }}"

    ###############################################
    # SAML SP Connector Configuration (BEFORE Transaction)
    ###############################################

    - name: Configure SAML SP Connector
      include_tasks: tasks/saml_sp_connector.yml
      tags:
        - saml
        - sp-connector

    ###############################################
    # SAML IDP Service Configuration (BEFORE Transaction)
    ###############################################

    - name: Configure SAML IDP Service
      include_tasks: tasks/saml_idp_service.yml
      tags:
        - saml
        - idp-service

    ###############################################
    # Transaction Start (For Policy Objects Only)
    ###############################################

    - name: Create transaction for policy configuration
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/transaction"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        body_format: json
        body: {}
        status_code: [200, 201]
        timeout: 30
      delegate_to: localhost
      register: transaction_result

    - name: Set transaction ID
      set_fact:
        transaction_id: "{{ transaction_result.json.transId }}"

    - name: Display transaction ID
      debug:
        msg: "Created transaction ID: {{ transaction_id }}"

    ###############################################
    # Access Policy with Logon Page and AD Auth (IN Transaction)
    ###############################################

    - name: Create Access Policy with Logon Page and AD Auth
      include_tasks: tasks/access_policy_solution4.yml
      tags:
        - policy
        - ad-auth

    ###############################################
    # Transaction Commit
    ###############################################

    - name: Commit transaction
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/transaction/{{ transaction_id }}"
        method: PUT
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        body_format: json
        body:
          state: "VALIDATING"
        status_code: [200, 409]
        timeout: 60
      delegate_to: localhost
      register: commit_result
      ignore_errors: yes

    - name: Display transaction commit status
      debug:
        msg: "{{ 'Transaction committed successfully' if commit_result.status == 200 else 'Objects already exist (idempotent run)' }}"
      when: commit_result.status in [200, 409]

    ###############################################
    # Apply Policy (Generate)
    ###############################################

    - name: Apply access policy (generate)
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/profile/access/~Common~{{ access_profile.name }}"
        method: PATCH
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        body_format: json
        body:
          generationAction: "increment"
        status_code: [200, 404]
        timeout: 60
      delegate_to: localhost
      register: policy_generation_result
      ignore_errors: yes

    - name: Display policy generation status
      debug:
        msg:
          - "{{ 'Policy generation completed' if policy_generation_result.status == 200 else 'Policy generation skipped (profile may not exist yet)' }}"
          - "Profile: {{ access_profile.name }}"
      when: policy_generation_result.status in [200, 404]

    ###############################################
    # Virtual Server via AS3 (Optional)
    ###############################################

    - name: Deploy AS3 Application with SAML IDP Profile
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/declare"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        body_format: json
        body: |
          {
            "class": "ADC",
            "action": "deploy",
            "persist": true,
            "declaration": {
              "class": "ADC",
              "schemaVersion": "3.14.0",
              "id": "APM-SAML-IDP",
              "{{ partition_name }}": {
                "class": "Tenant",
                "{{ vs1_name }}": {
                  "class": "Application",
                  "template": "generic",
                  "{{ vs1_name }}": {
                    "class": "Service_HTTPS",
                    "virtualAddresses": ["{{ as3_config.virtual_address }}"],
                    "virtualPort": {{ as3_config.virtual_port }},
                    "serverTLS": "{{ vs1_name }}-clientssl",
                    "snat": "{{ as3_config.snat }}",
                    "profileAccess": {
                      "bigip": "/Common/{{ access_profile.name }}"
                    }
                  },
                  "{{ vs1_name }}-clientssl": {
                    "class": "TLS_Server",
                    "certificates": [
                      {
                        "certificate": "tlsserver_local_cert"
                      }
                    ]
                  },
                  "tlsserver_local_cert": {
                    "class": "Certificate",
                    "certificate": {"bigip": "/Common/{{ as3_config.tls_cert_name }}"},
                    "privateKey": {"bigip": "/Common/{{ as3_config.tls_key_name }}"}
                  }
                }
              }
            }
          }
        status_code: [200, 201, 202]
        timeout: 120
      delegate_to: localhost
      when: create_as3_application | default(false)
      register: as3_result
      tags:
        - as3
        - virtual-server

    - name: Display AS3 deployment status
      debug:
        msg:
          - "AS3 deployment completed"
          - "Virtual Server: {{ as3_config.virtual_address }}:{{ as3_config.virtual_port }}"
          - "Access Profile: /Common/{{ access_profile.name }}"
      when:
        - create_as3_application | default(false)
        - as3_result.status in [200, 201, 202]

    ###############################################
    # GSLB Configuration (Optional)
    ###############################################

    - name: Deploy GSLB Wide-IP via AS3
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/declare"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ bigip_validate_certs }}"
        body_format: json
        body:
          class: "ADC"
          action: "deploy"
          persist: true
          declaration:
            class: "ADC"
            schemaVersion: "3.14.0"
            id: "GSLB"
            "{{ partition_name }}-gslb":
              class: "Tenant"
              "{{ vs1_name }}-gslb":
                class: "Application"
                template: "generic"
                "{{ gslb_config.wideip_name }}":
                  class: "GSLB_WideIP"
                  pools:
                    - "{{ gslb_config.pool_name }}"
                "{{ gslb_config.pool_name }}":
                  class: "GSLB_Pool"
                  members: "{{ gslb_config.pool_members | map('regex_replace', '^{\"ip\": \"(.+)\", \"port\": (\\d+)}$', '{\"server\": \"\\1\", \"virtualServer\": \"\\1:\\2\"}') | list }}"
        status_code: [200, 201, 202]
        timeout: 120
      delegate_to: localhost
      when: create_gslb | default(false)
      register: gslb_result
      tags:
        - gslb
        - dns

    - name: Display GSLB deployment status
      debug:
        msg:
          - "GSLB deployment completed"
          - "Wide-IP: {{ gslb_config.wideip_name }}"
          - "Pool: {{ gslb_config.pool_name }}"
      when:
        - create_gslb | default(false)
        - gslb_result.status in [200, 201, 202]

    ###############################################
    # Deployment Summary
    ###############################################

    - name: Display deployment summary
      debug:
        msg: |
          ============================================
          Deployment Complete!
          ============================================

          Solution: {{ vs1_name }}
          IDP Access URL: https://{{ dns1_name }}

          SAML IDP Configuration:
          - Identity Provider: {{ saml_idp_service.name }}
          - IDP Entity ID: {{ saml_idp_service.entity_id }}
          - Service Provider Connector: {{ saml_sp_connector.name }}
          - SP Entity ID: {{ saml_sp_connector.entity_id }}
          - Assertion Validity: {{ saml_idp_service.assertion_validity }}s

          Active Directory:
          - Domain: {{ ad_aaa_server.domain }}
          - AD Server: {{ ad_aaa_server.domain_controllers[0].name }} ({{ ad_aaa_server.domain_controllers[0].ip }})

          Access Policy:
          - Policy Name: {{ access_policy.name }}
          - Profile Name: {{ access_profile.name }}
          - Policy Timeout: {{ access_profile.access_policy_timeout }}s
          - Session Timeout: {{ access_profile.max_session_timeout }}s
          - SSO Service: {{ access_profile.sso_name }}

          {% if create_as3_application | default(false) %}
          Virtual Server:
          - IP: {{ as3_config.virtual_address }}:{{ as3_config.virtual_port }}
          - Access Profile: /Common/{{ access_profile.name }}
          {% endif %}

          {% if create_gslb | default(false) %}
          GSLB Configuration:
          - Wide-IP: {{ gslb_config.wideip_name }}
          - Pool: {{ gslb_config.pool_name }}
          {% endif %}

          Next Steps:
          1. Configure your Service Provider to trust this IDP
          2. Test authentication at https://{{ dns1_name }}
          3. Verify redirect to login page
          4. Test AD credential validation
          5. Verify SAML assertion issuance to SP
          6. Check APM logs at /var/log/apm for SAML events

          Troubleshooting:
          - Review SAML assertion in APM session variables
          - Check AD connectivity and credentials
          - Verify SP connector configuration matches your SP
          - Ensure DNS resolution for {{ dns1_name }} and {{ dns2_name }}

          Cleanup:
          To remove this deployment, run:
            ansible-playbook delete_apm_saml_idp.yml

          ============================================
      tags:
        - summary
