---
# Solution 8: OAuth Authorization Server Deployment
# BIG-IP APM as OAuth Authorization Server with AD Authentication
#
# This playbook deploys:
# - Active Directory AAA configuration (node, pool, server)
# - JWK (JSON Web Key) for JWT signing
# - OAuth Profile with token endpoints
# - Access Policy: Logon Page → AD Auth → AD Query → OAuth Authorization
# - AS3 Application deployment
# - Optional GSLB configuration
#
# Usage:
#   ansible-playbook deploy_apm_oauth_as.yml
#
# Prerequisites:
#   - BIG-IP with APM provisioned
#   - OAuth database (oauthdb) must exist on BIG-IP
#   - Active Directory server accessible from BIG-IP
#   - AS3 extension installed on BIG-IP

- name: Deploy OAuth Authorization Server (Solution 8)
  hosts: bigip
  gather_facts: no
  connection: local

  vars_files:
    - vars/solution8.yml

  tasks:
    # =========================================================================
    # VERIFY PREREQUISITES
    # =========================================================================

    - name: Verify AS3 is available
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/info"
        method: GET
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        status_code: [200]
      register: as3_info
      tags:
        - verify
        - always

    - name: Display AS3 version
      debug:
        msg: "AS3 version: {{ as3_info.json.version }}"
      tags:
        - verify

    # =========================================================================
    # ACTIVE DIRECTORY CONFIGURATION
    # =========================================================================

    - name: Create AD server node
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/ltm/node"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ ad_server_ip }}"
          address: "{{ ad_server_ip }}"
        status_code: [200, 201, 409]
      tags:
        - aaa
        - ad

    - name: Create AD server pool
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/ltm/pool/"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ ad_pool.name }}"
          members:
            - name: "{{ ad_server_ip }}:0"
              address: "{{ ad_server_ip }}"
              monitor: "{{ ad_pool.monitor }}"
        status_code: [200, 201, 409]
      tags:
        - aaa
        - ad

    - name: Create APM AAA Active Directory server
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/aaa/active-directory"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ ad_aaa_server.name }}"
          adminEncryptedPassword: "{{ ad_aaa_server.admin_password }}"
          adminName: "{{ ad_aaa_server.admin_name }}"
          domain: "{{ ad_aaa_server.domain }}"
          cleanupCache: "{{ ad_aaa_server.cleanup_cache }}"
          groupCacheTtl: "{{ ad_aaa_server.group_cache_ttl }}"
          kdcLockoutDuration: "{{ ad_aaa_server.kdc_lockout_duration }}"
          locationSpecific: "{{ ad_aaa_server.location_specific }}"
          padata: "{{ ad_aaa_server.padata }}"
          pool: "/Common/{{ ad_pool.name }}"
          psoCacheTtl: "{{ ad_aaa_server.pso_cache_ttl }}"
          timeout: "{{ ad_aaa_server.timeout }}"
          usePool: "{{ ad_aaa_server.use_pool }}"
          domainControllers: "{{ ad_aaa_server.domain_controllers }}"
        status_code: [200, 201, 409]
      tags:
        - aaa
        - ad

    # =========================================================================
    # JWK (JSON WEB KEY) CONFIGURATION
    # =========================================================================

    - name: Create JWK configuration for JWT signing
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/oauth/jwk-config/"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ jwk_config.name }}"
          partition: "{{ jwk_config.partition }}"
          algType: "{{ jwk_config.alg_type }}"
          autoGenerated: "{{ jwk_config.auto_generated }}"
          includeX5c: "{{ jwk_config.include_x5c }}"
          keyId: "{{ jwk_config.key_id }}"
          keyType: "{{ jwk_config.key_type }}"
          keyUse: "{{ jwk_config.key_use }}"
          sharedSecret: "{{ jwk_config.shared_secret }}"
          sharedSecretEncFormat: "{{ jwk_config.shared_secret_enc_format }}"
          useClientSecret: "{{ jwk_config.use_client_secret }}"
        status_code: [200, 201, 409]
      tags:
        - oauth
        - jwk

    # =========================================================================
    # OAUTH PROFILE CONFIGURATION
    # =========================================================================

    - name: Create OAuth profile
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/profile/oauth"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ oauth_profile.name }}"
          partition: "{{ oauth_profile.partition }}"
          defaultsFrom: "{{ oauth_profile.defaults_from }}"
          dbInstance: "{{ oauth_profile.db_instance }}"
          issuer: "{{ oauth_profile.issuer }}"
          accessTokenLifetime: "{{ oauth_profile.access_token_lifetime }}"
          authCodeLifetime: "{{ oauth_profile.auth_code_lifetime }}"
          idTokenLifetime: "{{ oauth_profile.id_token_lifetime }}"
          jwtAccessTokenLifetime: "{{ oauth_profile.jwt_access_token_lifetime }}"
          jwtRefreshTokenLifetime: "{{ oauth_profile.jwt_refresh_token_lifetime }}"
          refreshTokenLifetime: "{{ oauth_profile.refresh_token_lifetime }}"
          jwtToken: "{{ oauth_profile.jwt_token }}"
          opaqueToken: "{{ oauth_profile.opaque_token }}"
          generateJwtRefreshToken: "{{ oauth_profile.generate_jwt_refresh_token }}"
          generateRefreshToken: "{{ oauth_profile.generate_refresh_token }}"
          reuseAccessToken: "{{ oauth_profile.reuse_access_token }}"
          reuseRefreshToken: "{{ oauth_profile.reuse_refresh_token }}"
          perUserTokenLimit: "{{ oauth_profile.per_user_token_limit }}"
          refreshTokenUsageLimit: "{{ oauth_profile.refresh_token_usage_limit }}"
          jwtEcSignatureFormat: "{{ oauth_profile.jwt_ec_signature_format }}"
          jwtRefreshTokenEncSecret: "{{ oauth_profile.jwt_refresh_token_enc_secret }}"
          primaryKey: "{{ oauth_profile.primary_key }}"
          subject: "{{ oauth_profile.subject }}"
          openidConnect: "{{ oauth_profile.openid_connect }}"
          ignoreExpiredCert: "{{ oauth_profile.ignore_expired_cert }}"
          authUrl: "{{ oauth_profile.auth_url }}"
          tokenIssuanceUrl: "{{ oauth_profile.token_issuance_url }}"
          tokenIntrospectionUrl: "{{ oauth_profile.token_introspection_url }}"
          tokenRevocationUrl: "{{ oauth_profile.token_revocation_url }}"
          jwksUrl: "{{ oauth_profile.jwks_url }}"
          openidCfgUrl: "{{ oauth_profile.openid_cfg_url }}"
          userinfoUrl: "{{ oauth_profile.userinfo_url }}"
          clientApps:
            propertyDescriptions: {}
          idTokenClaims:
            propertyDescriptions: {}
          jwtAccessTokenClaims:
            propertyDescriptions: {}
          resourceServers:
            propertyDescriptions: {}
          rotationKeys:
            propertyDescriptions: {}
          userinfoClaims:
            propertyDescriptions: {}
        status_code: [200, 201, 409]
      tags:
        - oauth
        - profile

    # =========================================================================
    # ACCESS POLICY CONFIGURATION
    # =========================================================================

    - name: Configure access policy for OAuth Authorization Server
      include_tasks: tasks/access_policy_solution8.yml
      tags:
        - policy
        - access

    # =========================================================================
    # AS3 APPLICATION DEPLOYMENT
    # =========================================================================

    - name: Build TLS server certificate config
      set_fact:
        tls_cert_config:
          class: "Certificate"
          certificate:
            bigip: "/Common/{{ as3_config.tls_cert_name }}"
          privateKey:
            bigip: "/Common/{{ as3_config.tls_key_name }}"
      tags:
        - application
        - as3

    - name: Build TLS server profile config
      set_fact:
        tls_server_config:
          class: "TLS_Server"
          certificates:
            - certificate: "tlsserver_local_cert"
      tags:
        - application
        - as3

    - name: Build virtual server config
      set_fact:
        vs_config:
          class: "Service_HTTPS"
          virtualAddresses:
            - "{{ as3_config.virtual_address }}"
          virtualPort: 443
          serverTLS: "{{ vs1_name }}-clientssl"
          snat: "{{ as3_config.snat }}"
          profileAccess:
            bigip: "/Common/{{ vs1_name }}-psp"
      tags:
        - application
        - as3

    - name: Build application config
      set_fact:
        app_config:
          class: "Application"
          template: "generic"
      tags:
        - application
        - as3

    - name: Add virtual server to application
      set_fact:
        app_config: "{{ app_config | combine({vs1_name: vs_config}) }}"
      tags:
        - application
        - as3

    - name: Add TLS server profile to application
      set_fact:
        app_config: "{{ app_config | combine({vs1_name + '-clientssl': tls_server_config}) }}"
      tags:
        - application
        - as3

    - name: Add certificate to application
      set_fact:
        app_config: "{{ app_config | combine({'tlsserver_local_cert': tls_cert_config}) }}"
      tags:
        - application
        - as3

    - name: Build tenant config
      set_fact:
        tenant_config:
          class: "Tenant"
      tags:
        - application
        - as3

    - name: Add application to tenant
      set_fact:
        tenant_config: "{{ tenant_config | combine({vs1_name: app_config}) }}"
      tags:
        - application
        - as3

    - name: Build AS3 declaration
      set_fact:
        as3_declaration:
          class: "ADC"
          schemaVersion: "3.14.0"
          id: "APM"
      tags:
        - application
        - as3

    - name: Add tenant to declaration
      set_fact:
        as3_declaration: "{{ as3_declaration | combine({partition_name: tenant_config}) }}"
      tags:
        - application
        - as3

    - name: Build complete AS3 payload
      set_fact:
        as3_payload:
          class: "ADC"
          action: "deploy"
          persist: true
          declaration: "{{ as3_declaration }}"
      tags:
        - application
        - as3

    - name: Display AS3 declaration
      debug:
        var: as3_payload
        verbosity: 1
      tags:
        - application
        - as3

    - name: Deploy application using AS3
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/declare"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body: "{{ as3_payload }}"
        status_code: [200, 201, 202]
        timeout: 120
      register: as3_result
      tags:
        - application
        - as3

    - name: Display AS3 deployment result
      debug:
        msg: "AS3 deployment completed: {{ as3_result.json.results | default('Success') }}"
      tags:
        - application
        - as3

    # =========================================================================
    # GSLB CONFIGURATION (Optional)
    # =========================================================================

    - name: Configure GSLB for OAuth Authorization Server
      block:
        - name: Create DC1 datacenter
          uri:
            url: "https://{{ gslb_config.dns_server }}:443/mgmt/tm/gtm/datacenter"
            method: POST
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            validate_certs: "{{ validate_certs }}"
            body_format: json
            body:
              name: "{{ gslb_config.dc1.name }}"
            status_code: [200, 201, 409]

        - name: Create BIG-IP server in GTM
          uri:
            url: "https://{{ gslb_config.dns_server }}:443/mgmt/tm/gtm/server"
            method: POST
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            validate_certs: "{{ validate_certs }}"
            body_format: json
            body:
              name: "{{ gslb_config.dc1.bigip_server.name }}"
              datacenter: "/Common/{{ gslb_config.dc1.name }}"
              enabled: true
              product: "bigip"
              virtualServerDiscovery: "disabled"
              addresses:
                - name: "{{ gslb_config.dc1.bigip_server.address }}"
                  deviceName: "{{ gslb_config.dc1.bigip_server.name }}"
                  translation: "none"
            status_code: [200, 201, 409]

        - name: Add virtual server to GTM server
          uri:
            url: "https://{{ gslb_config.dns_server }}:443/mgmt/tm/gtm/server/~Common~{{ gslb_config.dc1.bigip_server.name }}/virtual-servers/"
            method: POST
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            validate_certs: "{{ validate_certs }}"
            body_format: json
            body:
              name: "/{{ partition_name }}/{{ vs1_name }}/{{ vs1_name }}"
              destination: "{{ as3_config.virtual_address }}:443"
            status_code: [200, 201, 409]

        - name: Build GSLB pool config
          set_fact:
            gslb_pool_config:
              class: "GSLB_Pool"
              enabled: true
              lbModeAlternate: "ratio"
              lbModeFallback: "ratio"
              manualResumeEnabled: false
              verifyMemberEnabled: true
              members:
                - ratio: 10
                  server:
                    bigip: "/Common/{{ gslb_config.dc1.bigip_server.name }}"
                  virtualServer: "/{{ partition_name }}/{{ vs1_name }}/{{ vs1_name }}"
              resourceRecordType: "A"

        - name: Build GSLB domain config
          set_fact:
            gslb_domain_config:
              class: "GSLB_Domain"
              domainName: "{{ gslb_config.wideip.domain_name }}"
              resourceRecordType: "{{ gslb_config.wideip.resource_record_type }}"
              poolLbMode: "{{ gslb_config.wideip.pool_lb_mode }}"
              lastResortPool:
                use: "{{ vs1_name }}-pool"
              lastResortPoolType: "A"
              pools:
                - use: "{{ vs1_name }}-pool"

        - name: Build GSLB application config
          set_fact:
            gslb_app_config:
              class: "Application"
              template: "generic"
              testDomain: "{{ gslb_domain_config }}"

        - name: Add GSLB pool to application
          set_fact:
            gslb_app_config: "{{ gslb_app_config | combine({vs1_name + '-pool': gslb_pool_config}) }}"

        - name: Build GSLB tenant config
          set_fact:
            gslb_tenant_config:
              class: "Tenant"

        - name: Add GSLB application to tenant
          set_fact:
            gslb_tenant_config: "{{ gslb_tenant_config | combine({vs1_name: gslb_app_config}) }}"

        - name: Build GSLB AS3 declaration
          set_fact:
            gslb_as3_declaration:
              class: "ADC"
              schemaVersion: "3.6.0"
              id: "GSLB_Sample"

        - name: Add GSLB tenant to declaration
          set_fact:
            gslb_as3_declaration: "{{ gslb_as3_declaration | combine({partition_name + '-gslb': gslb_tenant_config}) }}"

        - name: Deploy GSLB WideIP using AS3
          uri:
            url: "https://{{ gslb_config.dns_server }}:443/mgmt/shared/appsvcs/declare"
            method: POST
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            validate_certs: "{{ validate_certs }}"
            body_format: json
            body: "{{ gslb_as3_declaration }}"
            status_code: [200, 201, 202]
            timeout: 120
          register: gslb_result

        - name: Display GSLB deployment result
          debug:
            msg: "GSLB deployment completed"

      when: enable_gslb | default(false) | bool
      tags:
        - gslb
        - dns

    # =========================================================================
    # DEPLOYMENT SUMMARY
    # =========================================================================

    - name: Display deployment summary
      debug:
        msg: |
          ============================================================
          OAuth Authorization Server Deployment Complete
          ============================================================

          Virtual Server: https://{{ dns1_name }}
          Virtual Address: {{ as3_config.virtual_address }}:443

          OAuth Endpoints:
          - Authorization: https://{{ dns1_name }}{{ oauth_profile.auth_url }}
          - Token: https://{{ dns1_name }}{{ oauth_profile.token_issuance_url }}
          - Token Introspection: https://{{ dns1_name }}{{ oauth_profile.token_introspection_url }}
          - Token Revocation: https://{{ dns1_name }}{{ oauth_profile.token_revocation_url }}
          - JWKS: https://{{ dns1_name }}{{ oauth_profile.jwks_url }}
          - OpenID Config: https://{{ dns1_name }}{{ oauth_profile.openid_cfg_url }}
          - UserInfo: https://{{ dns1_name }}{{ oauth_profile.userinfo_url }}

          JWT Configuration:
          - Algorithm: {{ jwk_config.alg_type }}
          - Key ID: {{ jwk_config.key_id }}
          - Access Token Lifetime: {{ oauth_profile.jwt_access_token_lifetime }}s
          - Refresh Token Lifetime: {{ oauth_profile.jwt_refresh_token_lifetime }}s

          Access Policy: {{ vs1_name }}-psp
          - Logon Page → AD Auth → AD Query → OAuth Authorization

          ============================================================
      tags:
        - always
