---
# Solution 9: OAuth Resource Server Deployment
# Deploys BIG-IP APM as OAuth Resource Server (Client)
#
# PREREQUISITE: Solution 8 (OAuth Authorization Server) should be deployed first
#
# Usage:
#   # Default: External/Introspection mode (doesn't require OIDC discovery)
#   ansible-playbook deploy_apm_oauth_rs.yml
#
#   # Internal/JWT mode (requires OIDC discovery to succeed)
#   ansible-playbook deploy_apm_oauth_rs.yml -e token_validation_mode=internal
#
# Token Validation Modes:
# - external (default): Uses introspection to validate tokens against OAuth AS
#   This mode works even if OIDC discovery fails.
# - internal: Uses JWT validation with pre-shared key
#   This mode requires the OAuth AS to be reachable for OIDC discovery.
#
# This playbook creates:
# - OAuth Provider (pointing to Authorization Server's OIDC endpoint)
# - JWK Configuration (pre-shared key matching the Authorization Server)
# - JWT Provider List (only for internal mode, when OIDC discovery works)
# - OAuth Client Application
# - Access Policy with OAuth Scope validation
# - Access Profile
# - AS3 Application (Virtual Server, Pool, etc.)

- name: Deploy OAuth Resource Server (Solution 9)
  hosts: bigip
  gather_facts: no
  connection: local

  vars_files:
    - vars/solution9.yml

  tasks:
    # =========================================================================
    # DISPLAY DEPLOYMENT INFO
    # =========================================================================

    - name: Display deployment information
      debug:
        msg: |
          ============================================================
          Deploying Solution 9: OAuth Resource Server
          ============================================================
          Virtual Server: {{ vs1_name }}
          DNS Name: {{ dns1_name }}
          Virtual IP: {{ as3_config.virtual_address }}:{{ as3_config.virtual_port }}
          OAuth AS Reference: https://{{ oauth_as_dns }}
          Token Validation Mode: {{ token_validation_mode }}
          ============================================================
      tags:
        - always

    # =========================================================================
    # CREATE JWK CONFIGURATION
    # =========================================================================

    - name: Create JWK configuration
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/oauth/jwk-config"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ jwk_config.name }}"
          partition: "{{ jwk_config.partition }}"
          algType: "{{ jwk_config.alg_type }}"
          autoGenerated: "{{ jwk_config.auto_generated }}"
          includeX5c: "{{ jwk_config.include_x5c }}"
          keyId: "{{ jwk_config.key_id }}"
          keyType: "{{ jwk_config.key_type }}"
          keyUse: "{{ jwk_config.key_use }}"
          sharedSecret: "{{ jwk_config.shared_secret }}"
          sharedSecretEncFormat: "{{ jwk_config.shared_secret_enc_format }}"
          useClientSecret: "{{ jwk_config.use_client_secret }}"
        status_code: [200, 201, 409]
      register: jwk_result
      tags:
        - oauth
        - jwk

    - name: Display JWK creation result
      debug:
        msg: "JWK {{ jwk_config.name }}: {{ 'created' if jwk_result.status in [200, 201] else 'already exists' }}"
      tags:
        - oauth
        - jwk

    # =========================================================================
    # CREATE OAUTH PROVIDER
    # =========================================================================
    # The OAuth provider connects to the Authorization Server's OIDC endpoint.
    # For external mode, discovery isn't critical but improves functionality.
    # For internal mode, discovery is required to establish JWT config linkage.

    - name: Create OAuth provider
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/aaa/oauth-provider"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ oauth_provider.name }}"
          partition: "{{ oauth_provider.partition }}"
          allowSelfSignedJwkCert: "{{ oauth_provider.allow_self_signed_jwk_cert }}"
          discoveryInterval: "{{ oauth_provider.discovery_interval }}"
          ignoreExpiredCert: "true"
          introspect: "{{ oauth_provider.introspect }}"
          maxJsonNestingLayers: "{{ oauth_provider.max_json_nesting_layers }}"
          maxResponseSize: "{{ oauth_provider.max_response_size }}"
          openidCfgUri: "{{ oauth_provider.openid_cfg_uri }}"
          saveJsonPayload: "{{ oauth_provider.save_json_payload }}"
          trustedCaBundle: "/Common/ca-bundle.crt"
          type: "{{ oauth_provider.type }}"
          useAutoJwtConfig: "true"
        status_code: [200, 201, 409]
      register: oauth_provider_result
      tags:
        - oauth
        - provider

    - name: Display OAuth provider creation result
      debug:
        msg: "OAuth provider {{ oauth_provider.name }}: {{ 'created' if oauth_provider_result.status in [200, 201] else 'already exists' }}"
      tags:
        - oauth
        - provider

    # =========================================================================
    # CREATE JWT PROVIDER LIST (Internal Mode Only)
    # =========================================================================
    # JWT provider list requires OIDC discovery to succeed and create the
    # auto_jwt_<provider> config with proper linkage. Skip for external mode.

    - name: Create JWT provider list (internal mode only)
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/oauth/jwt-provider-list"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ jwt_provider_list.name }}"
          partition: "{{ jwt_provider_list.partition }}"
          accessTokenExpiresIn: "{{ jwt_provider_list.access_token_expires_in }}"
          providers: "{{ jwt_provider_list.providers }}"
        status_code: [200, 201, 409]
      register: jwt_list_result
      when: token_validation_mode == "internal"
      tags:
        - oauth
        - jwt

    - name: Display JWT provider list creation result
      debug:
        msg: "JWT provider list {{ jwt_provider_list.name }}: {{ 'created' if jwt_list_result.status in [200, 201] else 'already exists or skipped' }}"
      when: token_validation_mode == "internal"
      tags:
        - oauth
        - jwt

    - name: Display external mode info
      debug:
        msg: "Using external/introspection mode - JWT provider list not required"
      when: token_validation_mode == "external"
      tags:
        - oauth

    # =========================================================================
    # CREATE OAUTH CLIENT APPLICATION
    # =========================================================================

    - name: Create OAuth client customization group
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/policy/customization-group"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ vs1_name }}_oauth_authz_client_app_customization"
          partition: "Common"
          source: "/Common/standard"
          type: "oauth-authz-client-app"
        status_code: [200, 201, 409]
      tags:
        - oauth
        - client

    - name: Create OAuth client application
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/tm/apm/oauth/oauth-client-app"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body:
          name: "{{ oauth_client_app.name }}"
          partition: "{{ oauth_client_app.partition }}"
          appName: "{{ oauth_client_app.app_name }}"
          authType: "{{ oauth_client_app.auth_type }}"
          customizationGroup: "{{ oauth_client_app.customization_group }}"
          accessTokenLifetime: "{{ oauth_client_app.access_token_lifetime }}"
          authCodeLifetime: "{{ oauth_client_app.auth_code_lifetime }}"
          idTokenLifetime: "{{ oauth_client_app.id_token_lifetime }}"
          jwtAccessTokenLifetime: "{{ oauth_client_app.jwt_access_token_lifetime }}"
          jwtRefreshTokenLifetime: "{{ oauth_client_app.jwt_refresh_token_lifetime }}"
          refreshTokenLifetime: "{{ oauth_client_app.refresh_token_lifetime }}"
          refreshTokenUsageLimit: "{{ oauth_client_app.refresh_token_usage_limit }}"
          generateJwtRefreshToken: "{{ oauth_client_app.generate_jwt_refresh_token }}"
          generateRefreshToken: "{{ oauth_client_app.generate_refresh_token }}"
          reuseAccessToken: "{{ oauth_client_app.reuse_access_token }}"
          reuseRefreshToken: "{{ oauth_client_app.reuse_refresh_token }}"
          useProfileTokenMgmtSettings: "{{ oauth_client_app.use_profile_token_mgmt_settings }}"
          grantCode: "{{ oauth_client_app.grant_code }}"
          grantPassword: "{{ oauth_client_app.grant_password }}"
          grantToken: "{{ oauth_client_app.grant_token }}"
          openidConnect: "{{ oauth_client_app.openid_connect }}"
          redirectUris: "{{ oauth_client_app.redirect_uris }}"
        status_code: [200, 201, 409]
      register: oauth_client_result
      tags:
        - oauth
        - client

    - name: Display OAuth client application result
      debug:
        msg: "OAuth client application {{ oauth_client_app.name }}: {{ 'created' if oauth_client_result.status in [200, 201] else 'already exists' }}"
      tags:
        - oauth
        - client

    # =========================================================================
    # CREATE ACCESS POLICY
    # =========================================================================

    - name: Include access policy creation tasks
      include_tasks: tasks/access_policy_solution9.yml
      tags:
        - policy

    # =========================================================================
    # DEPLOY AS3 APPLICATION
    # =========================================================================

    # Build AS3 declaration in multiple steps to handle dynamic keys
    - name: Build AS3 application config
      set_fact:
        as3_app_config:
          class: "Application"
          template: "https"
          serviceMain:
            class: "Service_HTTPS"
            virtualAddresses:
              - "{{ as3_config.virtual_address }}"
            virtualPort: 443
            pool: "{{ vs1_name }}-pool"
            profileAccess:
              bigip: "/Common/{{ access_profile.name }}"
            serverTLS:
              bigip: "/Common/clientssl"
            redirect80: false
            snat: "{{ as3_config.snat }}"
      tags:
        - application
        - as3

    - name: Add pool to AS3 app config
      set_fact:
        as3_app_config: "{{ as3_app_config | combine({vs1_name + '-pool': {'class': 'Pool', 'monitors': ['http'], 'members': [{'servicePort': as3_config.pool_members[0].port | int, 'serverAddresses': [as3_config.pool_members[0].address]}]}}) }}"
      tags:
        - application
        - as3

    - name: Build AS3 tenant config
      set_fact:
        as3_tenant_config:
          class: "Tenant"
      tags:
        - application
        - as3

    - name: Add application to tenant
      set_fact:
        as3_tenant_config: "{{ as3_tenant_config | combine({path_name: as3_app_config}) }}"
      tags:
        - application
        - as3

    - name: Build AS3 declaration
      set_fact:
        as3_declaration:
          class: "AS3"
          action: "deploy"
          persist: true
          declaration:
            class: "ADC"
            schemaVersion: "3.0.0"
            id: "{{ partition_name }}"
      tags:
        - application
        - as3

    - name: Add tenant to declaration
      set_fact:
        as3_declaration: "{{ as3_declaration | combine({'declaration': as3_declaration.declaration | combine({partition_name: as3_tenant_config})}) }}"
      tags:
        - application
        - as3

    - name: Deploy AS3 application
      uri:
        url: "https://{{ bigip_mgmt }}:{{ bigip_port }}/mgmt/shared/appsvcs/declare"
        method: POST
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body: "{{ as3_declaration }}"
        status_code: [200, 202]
        timeout: 120
      register: as3_result
      tags:
        - application
        - as3

    - name: Display AS3 deployment result
      debug:
        msg: "AS3 application deployed: {{ as3_result.json.results[0].message | default('Success') }}"
      tags:
        - application
        - as3

    # =========================================================================
    # DEPLOYMENT SUMMARY
    # =========================================================================

    - name: Display deployment summary
      debug:
        msg: |
          ============================================================
          OAuth Resource Server Deployment Complete
          ============================================================

          Components Created:
          - OAuth Provider: {{ oauth_provider.name }}
          - JWK: {{ jwk_config.name }}
          - JWT Provider List: {{ jwt_provider_list.name if token_validation_mode == 'internal' else 'N/A (external mode)' }}
          - OAuth Client App: {{ oauth_client_app.name }}
          - Access Profile: {{ access_profile.name }}
          - AS3 Tenant: {{ partition_name }}

          Virtual Server Configuration:
          - Address: https://{{ as3_config.virtual_address }}:{{ as3_config.virtual_port }}
          - DNS Name: {{ dns1_name }}
          - Access Profile: {{ access_profile.name }}

          OAuth Configuration:
          - Authorization Server: https://{{ oauth_as_dns }}
          - OIDC Endpoint: {{ oauth_provider.openid_cfg_uri }}
          - Token Validation: {{ token_validation_mode }}

          ============================================================

          {% if token_validation_mode == 'external' %}
          NOTE: Using external/introspection mode. The OAuth AS must be
          reachable at runtime for token introspection to work.

          To use internal/JWT validation mode (requires OIDC discovery):
            ansible-playbook deploy_apm_oauth_rs.yml -e token_validation_mode=internal
          {% else %}
          NOTE: Using internal/JWT validation mode. OIDC discovery must
          have succeeded to create the auto_jwt config linkage.
          {% endif %}

          ============================================================
      tags:
        - always
